test(e2e): add e2e tests for notification
maxym-valor/fundamental-ngx pull request #58
Opened 2021-08-02 10:45 UTC by maxym-valor

#### Please provide a link to the associated issue.
Closes

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-08-31 14:44 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +        pause(1500);
why the pause here? could we use waitForElDisplayed instead?

2021-08-31 14:44 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +        expect(isElementDisplayed(defaultExample + notificationBody + avatar)).toBe(true, `avatar does not exist`);
could you please rework the selectors a bit. it's hard to read and debug when there are 3+ selectors being merged together.

2021-09-09 10:04 UTC, Seamoo13 commented
please squash

2021-09-13 11:43 UTC, Seamoo13 requested changes
please remove all non-e2e test file changes. (platform table component, etc)

2021-09-14 15:13 UTC, maxym-valor commented
> please remove all non-e2e test file changes. (platform table component, etc)

https://github.com/maxym-valor/fundamental-ngx/pull/86

2021-09-18 01:01 UTC, closed without merging